from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.

class NameAttack(models.Model):
	name = models.CharField(max_length=50)
	surname=models.CharField(max_length=8,primary_key=True)
	description = models.CharField(max_length=500)

	def __str__(self):
		return self.name

class DetailedAttack(models.Model):
	att=models.ForeignKey(NameAttack,on_delete=models.CASCADE)
	request=models.CharField(max_length=300,default='../')
	parameter=models.CharField(max_length=20,default='f')
	criticity = models.IntegerField(default=1)
	description=models.CharField(max_length=500)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.request

	def noblankrequest(self):
		if self.request=='../':
			raise ValidationError('Empty Request')

	def iscritical(self):
		return self.criticity>=3
	iscritical.boolean=True
	iscritical.short_description="Is it Critical ?"

	def correctcriticity(self):
		if self.criticity>5 or self.criticity<1:
			raise ValidationError('Incorrect criticity (between 1 and 5)')